[github]
local = "local/path/to/root1"
[github.repo1]
remote = "remote/path/to/repo1"

[bitbucket]
local = "local/path/to/root2"
[bitbucket.repo1]
remote = "remote/path/to/repo1"

[work]
local = "/home/johndoe/work/"
[work.projectbackend]
remote = "git@mycompany.com:johndoe/projectbackend"
[work.projectfrontend]
remote = "git@mycompany.com:johndoe/projectfrontend"

[personal]
local = "/home/johndoe/git/"
[personal.myorgmodenotes]
remote = "git@github.com:johndoe/myorgmodenotes"
[personal.mysideproject]
remote = "git@github.com:johndoe/mysideproject"
