[github]
path = "local/path/to/root1"

[github.repo1]
name = "Repo1"
path = "remote/path/to/root1"

[bitbucket]
path = "local/path/to/root2"

[bitbucket.repo3]
name = "Repo3"
path = "remote/path/to/root2/repo3"
