name: Go

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Matches tags like v0.1, v1.0, etc.
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o gogit-linux

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o gogit-windows.exe

    - name: Build for Mac
      run: GOOS=darwin GOARCH=amd64 go build -o gogit-mac

    - name: Test
      run: go test

    - name: Check Tag
      id: check_tag
      run: echo "GITHUB_REF=${GITHUB_REF}"

    - name: Create Release
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Linux Executable
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gogit-linux
        asset_name: gogit-linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Executable
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gogit-windows.exe
        asset_name: gogit-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Mac Executable
      if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gogit-mac
        asset_name: gogit-mac
        asset_content_type: application/octet-stream
